### ISSUE TITLE
Sistema Top!!!

### ISSUE THREAD

**Issue by rafatosta** [Gusrrocha/Sistema-para-livraria#1]
Gostei! Está bem organizado.
Só está dando erro no cadastro, mas esperarei as próximas versões.

**Comment by rafatosta** [comment]
![image](https://user-images.githubusercontent.com/18619894/150877361-f09efedc-b58c-4e84-9ded-cb1ce247094d.png)
Por favor, oculte o campo de senha através da opção:
![image](https://user-images.githubusercontent.com/18619894/150877485-3967b83d-7cf9-40dc-b2f0-e8062c2f7095.png)

Obrigado.
=D

**Comment by Gusrrocha** [comment]
> Gostei! Está bem organizado. Só está dando erro no cadastro, mas esperarei as próximas versões.

Ainda está dando erro? Só vi seu comentário agora, provável que eu já tenha resolvido...
